///
/// @Generated by Mockolo
///

@testable import CI_T_Movie_Database
import Combine
import Foundation

class APIManagerServiceMock: APIManagerService {
    private(set) var fetchItemsCallCount = 0
    var fetchItemsHandler: ((URL, Any) -> Void)?
    func fetchItems<T: Decodable>(url: URL, completion: @escaping (Result<T, Error>) -> Void) {
        fetchItemsCallCount += 1
        if let fetchItemsHandler = fetchItemsHandler {
            fetchItemsHandler(url, completion)
        }
    }
}
