///
/// @Generated by Mockolo
///

@testable import CI_T_Movie_Database
import Foundation

class GenresRepositoryProtocolMock: GenresRepositoryProtocol {
    var model: [MovieGenre] = []
    var error: Error!

    private(set) var getGenresCallCount = 0
    var getGenresHandler: ((@escaping (Result<[MovieGenre], Error>) -> Void) -> Void)?
    func getGenres(completion: @escaping (Result<[MovieGenre], Error>) -> Void) {
        getGenresCallCount += 1
        if let getGenresHandler = getGenresHandler {
            getGenresHandler(completion)
        }

        if let error = error {
            completion(.failure(error))
        } else {
            completion(.success(model))
        }
    }
}
