///
/// @Generated by Mockolo
///

@testable import CI_T_Movie_Database
import Foundation

class MovieDetailRepositoryProtocolMock: MovieDetailRepositoryProtocol {
    var model: MovieDetail!
    var error: Error!

    private(set) var getMovieDetailsByCallCount = 0
    var getMovieDetailsByHandler: ((Int, @escaping (Result<MovieDetail, Error>) -> Void) -> Void)?
    func getMovieDetailsBy(movieId: Int, completion: @escaping (Result<MovieDetail, Error>) -> Void) {
        getMovieDetailsByCallCount += 1
        if let getMovieDetailsByHandler = getMovieDetailsByHandler {
            getMovieDetailsByHandler(movieId, completion)
        }

        if let error = error {
            completion(.failure(error))
        } else {
            completion(.success(model))
        }
    }
}
